# Generated by Django 4.0.4 on 2022-05-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("explore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date this record was created."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date this record was most recently modified.",
                    ),
                ),
                ("name", models.SlugField(help_text="The name of the event.")),
                (
                    "title",
                    models.CharField(help_text="The displayed title.", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date this record was created."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date this record was most recently modified.",
                    ),
                ),
                ("name", models.SlugField(help_text="The name of the event.")),
                (
                    "title",
                    models.CharField(help_text="The displayed title.", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="The description of the origin."),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_stations",
                        to="explore.area",
                    ),
                ),
                (
                    "coordinate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="water_stations",
                        to="explore.coordinate",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="water_stations",
                        to="explore.origin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date this record was created."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date this record was most recently modified.",
                    ),
                ),
                (
                    "issued_date",
                    models.DateTimeField(
                        editable=False, help_text="The date this record was issued."
                    ),
                ),
                (
                    "retrieved_date",
                    models.DateTimeField(
                        editable=False, help_text="The date this record was retrieved."
                    ),
                ),
                (
                    "occurred_date",
                    models.DateTimeField(
                        editable=False, help_text="The date this record occurred."
                    ),
                ),
                ("level", models.FloatField(help_text="The value of the measurement.")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("observed_height", "Observed height"),
                            ("obtained_sample", "Obtained sample"),
                            ("forecast_height", "Forecast height"),
                            ("threshold", "Threshold"),
                        ],
                        help_text="The measure type.",
                        max_length=20,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("not_tested", "Not tested"),
                            ("warn_minor", "Minor warning"),
                            ("warn_moderate", "Moderate warning"),
                            ("warn_major", "Major warning"),
                        ],
                        help_text="The measure quality or status.",
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurements",
                        to="water.group",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="water.station",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("name",), name="water_group_unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("origin", "name"), name="water_station_unique_origin_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="measure",
            constraint=models.UniqueConstraint(
                fields=("occurred_date", "station"),
                name="water_measure_unique_occurred_date_station",
            ),
        ),
    ]
