# Generated by Django 4.0.4 on 2022-05-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("water", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="level",
            field=models.FloatField(
                blank=True, help_text="The value of the measurement.", null=True
            ),
        ),
    ]
