documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - requirements.txt
          - requirements-dev.txt
          - pyproject.toml
          - MANIFEST.in

tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**/*
