[tool.poetry]
name = "gather-vision"
version = "0.2.0"
description = "A collection of data and ideas related to society and government in Queensland, Australia."
license = "Apache-2.0"
authors = [
    "Mark Cottman-Fields <cofiem@gmail.com>"
]
readme = "README.md"
homepage = "https://github.com/anotherbyte-net/gather-vision"
repository = "https://github.com/anotherbyte-net/gather-vision"
documentation = "https://github.com/anotherbyte-net/gather-vision"
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Django",
]


[tool.poetry.dependencies]
python = "^3.9"

# general
Django = "^4.0"
docutils = "^0.18"
requests = "^2.26.0"
requests-cache = "^0.8.1"
django-environ = "^0.8.1"

# calendar
ics = "^0.7"
icalendar = "^4.0.9"

# music
ytmusicapi = "^0.19.4"
xmltodict = "^0.12.0"
lxml = "^4.6.4"
django-debug-toolbar = "^3.2.2"


[tool.poetry.dev-dependencies]
black = "^21.10b0"
flake8 = "^3.9.2"
requests-mock = "^1.9.3"
coverage = "^6.2"
django-coverage-plugin = "^2.0.2"
pytest = "^6.2.5"
flake8-django = "^1.1.2"
flake8-bugbear = "^21.9.2"
tblib = "^1.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
gather-vision = "manage:main"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --quiet"
testpaths = [
    "gather_vision/tests",
]
python_files = [
    'tests.py',
    'test_*.py',
    '*_tests.py',
]
DJANGO_SETTINGS_MODULE = 'gather_vision_proj.settings'

[tool.coverage.run]
# "Specifying the source option enables coverage.py to report on unexecuted files,
# since it can search the source tree for files that haven’t been measured at all."
source = [
    "gather_vision",
    "gather_vision_proj",
    "templates",
]
omit = [
    "*/site-packages/*",
    "*/tests/*",
    "gather_vision/migrations/",
]
plugins = [
    "django_coverage_plugin",
]

[tool.coverage.report]
skip_empty = true

[tool.coverage.html]
directory = "coverage-html"

[tool.black]
line-length = 88
target-version = [
    "py38",
    "py39",
    "py310",
]
extend-exclude = """
# Exclude files in addition to the defaults.
# A regex preceded with ^/ will apply only to files and directories in the root of the project.
gather_vision/migrations
"""
