[tool.poetry]
name = "gather-vision"
version = "0.1.0"
description = ""
authors = ["Mark Cottman-Fields <cofiem@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

# general
Django = "^3.2.9"
docutils = "^0.18"
requests = "^2.26.0"
requests-cache = {extras = ["sqlite"], version = "^0.8.1"}
feedparser = "^6.0.8"

# calendar
ics = "^0.7"
icalendar = "^4.0.9"

# music
ytmusicapi = "^0.19.4"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
flake8 = "^4.0.1"
requests-mock = "^1.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
