# Generated by Django 4.0.4 on 2022-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date this record was created."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date this record was most recently modified.",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, help_text="The date this event started.", null=True
                    ),
                ),
                (
                    "stop_date",
                    models.DateField(
                        blank=True, help_text="The date this event stopped.", null=True
                    ),
                ),
                ("name", models.SlugField(help_text="The name of the event.")),
                (
                    "title",
                    models.CharField(help_text="The displayed title.", max_length=200),
                ),
                (
                    "url",
                    models.URLField(blank=True, help_text="A link to event details."),
                ),
                (
                    "locations",
                    models.CharField(
                        blank=True,
                        help_text="The name of the locations and streets involved in the event.",
                        max_length=600,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date this record was created."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date this record was most recently modified.",
                    ),
                ),
                (
                    "issued_date",
                    models.DateTimeField(
                        editable=False, help_text="The date this record was issued."
                    ),
                ),
                (
                    "retrieved_date",
                    models.DateTimeField(
                        editable=False, help_text="The date this record was retrieved."
                    ),
                ),
                (
                    "occurred_date",
                    models.DateTimeField(
                        editable=False, help_text="The date this record occurred."
                    ),
                ),
                (
                    "affected",
                    models.PositiveIntegerField(
                        help_text="The number of customers or other entities affected by the event."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date this record was created."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date this record was most recently modified.",
                    ),
                ),
                (
                    "issued_date",
                    models.DateTimeField(
                        editable=False,
                        help_text="The date this usage was issued by the origin.",
                    ),
                ),
                (
                    "retrieved_date",
                    models.DateTimeField(
                        editable=False,
                        help_text="The date this usage was retrieved from the origin.",
                    ),
                ),
                (
                    "occurred_date",
                    models.DateTimeField(
                        editable=False, help_text="The date this record occurred."
                    ),
                ),
                (
                    "demand",
                    models.PositiveIntegerField(
                        help_text="The measure of electricity demand in megawatts."
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="The rating of the demand level."
                    ),
                ),
                (
                    "customers",
                    models.PositiveIntegerField(
                        help_text="The number of customers or other entities causing the demand."
                    ),
                ),
            ],
        ),
    ]
