# Generated by Django 4.0.4 on 2022-05-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("explore", "0002_alter_area_name_alter_origin_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date this record was created."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date this record was most recently modified.",
                    ),
                ),
                (
                    "issued_date",
                    models.DateTimeField(
                        editable=False, help_text="The date this record was issued."
                    ),
                ),
                (
                    "retrieved_date",
                    models.DateTimeField(
                        editable=False, help_text="The date this record was retrieved."
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, help_text="The date this event started.", null=True
                    ),
                ),
                (
                    "stop_date",
                    models.DateField(
                        blank=True, help_text="The date this event stopped.", null=True
                    ),
                ),
                ("name", models.SlugField(help_text="The name of the event.")),
                (
                    "title",
                    models.CharField(help_text="The displayed title.", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="The description of the event."),
                ),
                (
                    "url",
                    models.URLField(blank=True, help_text="A link to event details."),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("train_track", "Train track"),
                            ("train_station", "Train station"),
                            ("train_carpark", "Train carpark"),
                            ("train_accessibility", "Train accessibility"),
                            ("bus_stop", "Bus stop"),
                        ],
                        help_text="The infrastructure affected by the event.",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("minor", "Minor"),
                            ("major", "Major"),
                        ],
                        help_text="The severity of the event.",
                        max_length=20,
                    ),
                ),
                (
                    "locations",
                    models.CharField(
                        blank=True,
                        help_text="The locations covered by the event.",
                        max_length=500,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date this record was created."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date this record was most recently modified.",
                    ),
                ),
                ("name", models.SlugField(help_text="The name of the group.")),
                (
                    "title",
                    models.CharField(help_text="The displayed title.", max_length=200),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("ferry", "Ferry"),
                            ("train", "Train"),
                            ("tram", "Tram"),
                        ],
                        help_text="The type of transport.",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="transport_group_unique_name_category"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transport_events",
                to="explore.area",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="groups",
            field=models.ManyToManyField(
                help_text="The groups involved in this event.",
                related_name="events",
                to="transport.group",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transport_events",
                to="explore.origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("origin", "name"), name="transport_event_unique_origin_name"
            ),
        ),
    ]
