# Generated by Django 4.2.5 on 2023-09-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="occurred_date",
            field=models.DateTimeField(
                help_text="The date this record occurred.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True, help_text="The description of the record."
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="issued_date",
            field=models.DateTimeField(
                help_text="The date this record was issued.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="modified_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date this record was most recently changed.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.SlugField(help_text="The internal name of the record."),
        ),
        migrations.AlterField(
            model_name="event",
            name="retrieved_date",
            field=models.DateTimeField(help_text="The date this record was retrieved."),
        ),
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(
                blank=True, help_text="A link to the record details."
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="modified_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The date this record was most recently changed.",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.SlugField(help_text="The internal name of the record."),
        ),
    ]
