# Generated by Django 5.0a1 on 2023-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0003_event_gatherer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("train_track", "Train track"),
                    ("train_station", "Train station"),
                    ("train_carpark", "Train carpark"),
                    ("train_accessibility", "Train accessibility"),
                    ("bus_stop", "Bus stop"),
                    ("ferry_terminal", "Ferry terminal"),
                    ("train_service", "Train service"),
                    ("bus_service", "Bus service"),
                    ("ferry_service", "Ferry service"),
                ],
                help_text="The infrastructure affected by the event.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.SlugField(
                help_text="The internal name of the record.", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(help_text="The displayed title.", max_length=300),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.SlugField(
                help_text="The internal name of the record.", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(help_text="The displayed title.", max_length=300),
        ),
    ]
