# Generated by Django 5.0a1 on 2023-09-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explore", "0003_alter_area_modified_date_alter_area_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gatherer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The date this record was created."
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date this record was most recently changed.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="The description of the record."
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="A link to the record details."
                    ),
                ),
                (
                    "name",
                    models.SlugField(help_text="The internal name of the record."),
                ),
                (
                    "title",
                    models.CharField(help_text="The displayed title.", max_length=200),
                ),
                (
                    "gather_type",
                    models.CharField(
                        help_text="The gather data type name.", max_length=300
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="gatherer",
            constraint=models.UniqueConstraint(
                fields=("name", "gather_type"),
                name="explore_gatherer_unique_name_gather_type",
            ),
        ),
    ]
