"""
Django settings for gather_vision project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from importlib import resources
from gather_vision_proj.gather_vision_env import GatherVisionEnv


# Use django-environ to load settings.
env = GatherVisionEnv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
with resources.path("gather_vision_proj", "settings.py") as p:
    BASE_DIR = p.resolve().parent.parent

# Load the settings from the env file.
# Check the DJANGO_ENV_FILE env var first, then default to local .env file.
env.read_env(env.str("DJANGO_ENV_FILE", BASE_DIR / ".env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", str, [])
INTERNAL_IPS = env.list("INTERNAL_IPS", str, ["127.0.0.1"])


# Installed applications
# https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-INSTALLED_APPS
INSTALLED_APPS = [
    "django.contrib.admindocs",
    "gather_vision_proj.apps.GatherVisionAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "gather_vision.apps.GatherVisionConfig",
    "debug_toolbar",
]

# Middleware: Django 'plugins' to alter input and output
# https://docs.djangoproject.com/en/4.0/topics/http/middleware/
MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Root URL conf: import path for the project-level url conf.
# https://docs.djangoproject.com/en/4.0/ref/settings/#root-urlconf
ROOT_URLCONF = "gather_vision_proj.urls"

# Django template engines.
# https://docs.djangoproject.com/en/4.0/ref/settings/#templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI app for the Django dev server.
# https://docs.djangoproject.com/en/4.0/ref/settings/#wsgi-application
WSGI_APPLICATION = "gather_vision_proj.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {"default": env.db_url()}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGE_CODE = "en-au"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cache
# https://docs.djangoproject.com/en/4.0/topics/cache
CACHES = {"default": env.cache_url()}

# (custom) External HTTP client cache
# Works in a similar way to Django's cache settings.
# https://requests-cache.readthedocs.io/en/stable/user_guide/backends.html
EXTERNAL_HTTP_CACHES = {"default": env.external_http_cache_url()}

# (custom) Playlist sources and targets.
PLAYLIST_SOURCES_TARGETS = env.playlist_sources_targets()

# (custom) Playlist service config
SPOTIFY_AUTH_REFRESH_TOKEN = env.str("SPOTIFY_AUTH_REFRESH_TOKEN", None)
SPOTIFY_AUTH_CLIENT_ID = env.str("SPOTIFY_AUTH_CLIENT_ID", None)
SPOTIFY_AUTH_CLIENT_SECRET = env.str("SPOTIFY_AUTH_CLIENT_SECRET", None)
SPOTIFY_AUTH_REDIRECT_URI = env.str("SPOTIFY_AUTH_REDIRECT_URI", None)

YOUTUBE_MUSIC_AUTH_CONFIG = env.str("YOUTUBE_MUSIC_AUTH_CONFIG", None)

LASTFM_AUTH_API_KEY = env.str("LASTFM_AUTH_API_KEY", None)
