# Generated by Django 4.0 on 2022-01-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gather_vision', '0003_alter_petitionchange_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQualitySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date this item was created.')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='The date this item was last changed.')),
                ('code', models.CharField(help_text='The site reference code.', max_length=10)),
                ('title', models.CharField(help_text='The title of the site.', max_length=100)),
                ('description', models.TextField(help_text='The description of the site.')),
                ('latitude', models.DecimalField(decimal_places=5, help_text='The latitude or North/South position.', max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, help_text='The longitude or East/West position.', max_digits=8)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_sites', to='gather_vision.informationsource')),
            ],
        ),
        migrations.CreateModel(
            name='WaterQualitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date this item was created.')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='The date this item was last changed.')),
                ('retrieved_date', models.DateTimeField(help_text='The date this item was retrieved from the source.')),
                ('sample_date', models.DateTimeField(help_text='The date this sample was conducted.')),
                ('sample_value', models.PositiveIntegerField(blank=True, help_text='The value of the sample.', null=True)),
                ('sample_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('not_tested', 'Not tested')], help_text='The status of the sample.', max_length=20)),
                ('site', models.ForeignKey(help_text='The sample site.', on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='gather_vision.waterqualitysite')),
            ],
        ),
        migrations.AddConstraint(
            model_name='waterqualitysite',
            constraint=models.UniqueConstraint(fields=('source', 'code'), name='water_quality_site_unique_source_code'),
        ),
        migrations.AddConstraint(
            model_name='waterqualitysample',
            constraint=models.UniqueConstraint(fields=('site', 'sample_date'), name='water_quality_sample_unique_site_date'),
        ),
    ]
