# Generated by Django 4.0 on 2022-01-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather_vision', '0004_waterqualitysite_waterqualitysample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualitysample',
            name='sample_status',
            field=models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('not_tested', 'Not tested')], default='not_tested', help_text='The status of the sample.', max_length=20),
        ),
    ]
