# Generated by Django 4.0 on 2022-01-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gather_vision', '0005_alter_waterqualitysample_sample_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterqualitysample',
            name='sample_date',
            field=models.DateField(help_text='The date this sample was conducted.'),
        ),
    ]
